spring:
  application:
    name: Task Management

  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_db
    username: task_management_user
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: scj6biz7a6xv2wnIBdtQrfuQ3OgG4dl3WM52wGAkPyA=
  access-token-expiration: 900000 # 15 minutes
