spring:
  application:
    name: Task Management

  datasource:
    url: jdbc:postgresql://localhost:5432/task_management_db
    username: task_management_user
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
